# Exercises in Python programming

**Q.1.** Write a program to assign a number to a variable and print the square and cube of the number. 

**Q.2.** Write a program to print the reminder of a number, larger than 3, divided by 3. Use module operator.

**Q.3.** Write a program to print all odd numbers between any two numbers. Use `while` loop and `if` condition.

**Q.4.** Write a function to check whether a number is prime or not. 

**Q.5.** Using `for` loop and `range` iterator print square of all numbers less than a number n.

**Q.6.** Define an empty list (i.e., say, a = [ ]). Modify the above program to append the square of numbers in to this empty list. 

a. Finally print the list of numbers. 

b. Print the first two and last twonumbers

c. Print the third to 6th elements.

**Q.7.** What happens when you add, subtract, multiply or divide a list by a number.

**Q.8.** Define two lists of numbers and find out the results of four arithmetic operations between two lists. 

**Q.9.** Define an array of 5 elements. Explore the four arithmetic operations on the array by a number.

**Q.10.** Define two arrays of 5 elements each. What happens when you add, subtract, multipy or divide these arrays.

**Q.11.** Create a 4X5 array of all ones (use np.ones)

**Q.12.** Create an 5X4 array of all zeros ( use np.zeros)

**Q.13.** Print the last two rows of the array 'a' and two columns of a.

In [11]:
import numpy as np

In [12]:
a = np.random.random([5,6])
print a

[[0.34141715 0.67445508 0.70012974 0.27512986 0.33954006 0.23969668]
 [0.15536315 0.77433789 0.83235955 0.64607676 0.69277715 0.86662666]
 [0.65638833 0.38425824 0.63162095 0.63418708 0.60810526 0.75957721]
 [0.87401061 0.30144742 0.30514688 0.28027768 0.35097627 0.39537572]
 [0.96245578 0.62792409 0.16413639 0.61941806 0.49493195 0.0123546 ]]


**Q.14.** (a) Debug the following code to print numbers from 10 to 1. (a) Modify the while loop to stop the code when i = 3. (c) How would you modify the loop to skip printing the number 3? 

In [19]:
i =10
while i >0
print i,
i -= 1

SyntaxError: invalid syntax (<ipython-input-19-aca508cae0b0>, line 2)

**Q.15.** Pascal's triangle :

   a. Write a function `binomial(n,k)` to compute binomial 
    coefficient. Make sure to return answers as integer. 
    Make sure that it gives $1$ for `k=0`.
    
   b. Print out first 10 lines of Pascals triangle 
    i.e n$_{\rm th}$ line will contain binomial(n,0), 
    binomial(n,1), ..., binomial(n,n).
    
   c. Probability of obtaining k heads in n tosses is 
    `binomial(n,k)/2**n`. Write a program to calculate 
    probability of obtaining 40 heads in 100 tosses. 
    Write a program to calculate 40 or more heads in 
    100 tosses. 