# Introduction to Python

In this notebook, we will learn some basics of programming using Python.

A program consists of a list of instructions or statements which the computer will execute one by one. The following sections introduce various types of statements in the Python language.

### Variables and Assignments

In [ ]:
# Assignment statement: i.e. assign a value to a variable. Eg.
x = 1
# The above statement tells the computer that there is a variable x which has value 1.

#### Rules in naming variables

1. Variables can contain alphabets, '_' and numbers.
2. Variables cannot start with a number

Eg. : abc, star_123, _xft etc. are valid variables. 

While doing Physics problems, the code becomes more readable if we use variables such as 'angular_momentum', 'velocity_initial' etc.

### Variable types

1. Integers : 0, 1, 2345, -7862
2. Float : 3.14159, -1.0, -6.63e-34
3. Complex : 1 + 2j, -3.5 -0.8j

In [ ]:
#Integers
-3496

In [ ]:
#Float
-6.63e-3

In [ ]:
# Complex
-1. + 3.4j

Note that:

* Type of variable is set by the value assigned to it
* Storage size used by these variables types are different. 


Another variable type:

* String: 

x = "This is a string"
Strings are a set of characters. Even numbers can be a string. Eg:- x = "1.453". In this example, x does not represent a number, but a set of symbols  which are numbers and a decimal.

### Output and Input Statement

Out put statement is `print` and input statement is `input`

In [ ]:

x = 1
print x
# If you are using Python 3, print is a function and hence so you should write print(x). 

In [ ]:
y =5.6
print x, y

In [ ]:
thevalueof = "The value of"
print thevalueof, "x is", x, "and", thevalueof,"y is", y

In [ ]:
thevalueof = "The square of"
print thevalueof, "x is", x*x, "and", thevalueof,"y is", y*y

In [ ]:
#input statement
x = input("Enter the value of x")
print x

In [ ]:
x = input("Enter the value of x:")
print x

In [ ]:
temp = input("Enter the value of x :")
print "The value of temp is :", temp
x=int(temp)
print "The value of x is :", x
# Run this code and give temp = "0.5", i.e. as a string. Observe the output. 
# Now rerun the code by changing `float` in the third line to `complex` and 
#`int` and see what happens.

In [ ]:
x="5"
int(x)

### Arithmetic

In [ ]:
x =4
y = 2

In [ ]:
# Addition
x+y

In [ ]:
# Subtraction
x-y

In [ ]:
# Multiplication
x*y

In [ ]:
# Division
x/y

In [ ]:
# Raising x to the power y
x**y

In [ ]:
# Integer division
# As noted above, when we divide two integers, 
# the result gets rounded down to its nearest integer.
x=14.
y=3
x//y

In [ ]:
#Modulo operator
x=15
y=4
x%y

# This operator can be used to find for instance 
# whether a number is even or odd.

#### Combining mathematical operators

`x + 2*y`    is equivalent to    $x + 2y$

`x - y/2`    is equivalent to    $x - y/2$

`3*x**2`    is equivalent to   $3*x^2$

`x/2*y`    is equivalent to $\frac{1}{2}x y$

One can also use brackets to separate out operators. Eg:- Note the difference

`x = a + b/c`

`x = (a +b)/c`

`x = a + 2*b - 0.5*(1.5**c + 2/7)`

Also note that, operations are only allowed on right side, not on the left side. Eg:-

`2*x = y`

is not allowed.

In [ ]:
2*x = y

In [ ]:
# Note that 
x = 1
# is an assignment, not an equation. 
# One can also do
x = x + 1
print x
# Mathematically the above statement does not make much sense.

#### Python modifiers

`x+=1`    add 1 to x and assign it to x

`x-=2`    subtract 2 from x and assign it to x

`x *= -1.5' multipy x by -1.5 and assign it to x

`x /= 3*x`  divide by $3\times x$ and assign it to x

'x //=1.4`    divide by 1.4 and round down to a whole number and assign it to x

In [ ]:
x = 3
x += 2
print x

### Importing functions from packages

In [3]:
x = 10
log(x)

NameError: name 'log' is not defined

In [4]:
from math import log
x = log(x)
print x

2.30258509299


In [5]:
from math import log10
x = 10
print log10(x)

1.0


`math` package will allow us to use many such functions:

`log`, `log10`, `exp`, `sin`, `cos`, `tan`, `asin`, `acos`, `atan`, `sinh`, `cosh`, `tanh`, `sqrt`


In [6]:
# It also gives you the value of pi
from math import pi
print pi

3.14159265359


If you want you can import more than one function in single line

`from math import log, sin, cos`

will load three functions simultaneously. 
There are many other useful packages. You can look up the package `numpy` .

### Modules
Sometimes, packages contain modules which contain a 
particular set of functions. For instance, numpy contains 
a linear algebra module which contains a lot of functions 
such as inverse.

In [7]:
import numpy.linalg as linalg

### Summary : An example program

In [ ]:
from math import sin, cos, pi
# Ask the user to enter values for radius and angle
r = input("Enter r = ")
degree = input("Enter theta in degrees =")

# Covert degree to radians

theta = degree*pi/180

# Convert (r, theta) to equivalent cartesian coordinates

x = r*cos(theta)
y = r*sin(theta)

# Output results

print "x=", x, "and y=", y

### Controlling programs with **if** and **while**

#### The if statement

The `if` statement executes an expression only if certain condition is satisfied. It has the format

```
if condition :
       instruction 1
       
       instruction 2
       
       ...
       
       instruction n
```
Note the semicolon and the indent. It tells the code which part should be evaluated when the condition is satisfied.

Conditions are of various types:

* `if x==1`   => Chack if $x=1$. Note the two equal signs

* `if x>1`

* `if x>=1`

* `if x<1`

* `if x<=1`

* `if x!=1`    => Check if $x \neq 1$


In [ ]:
# A program to alert the user when they enter a number larger than 10

x = int(input("Enter a whole number less than or equal to 10: "))
if x>10:
    print "You entered a number larger than 10."
    print "Re-assigning the number as 10!"
    x = 10
print "The number you entered is :", x

#### Relational operators
` >, <, ==, >=, <=, !=` are relational operators. Their anser is `True` or `False`.

#### Boolean operators in python
1. and
2. or
3. not

In [13]:
x=20
y=30
x>y

False

In [ ]:
x>0  and y>0

In [ ]:
x>0 or y<10

In [ ]:
not(x>0 and y>0)

In [10]:
# One can use more than one conditions in if statement
x = input("enter x between 1 and 10:")
if x>10 or x<1:
    print "Number is out of bound"

enter x between 1 and 10: 5


#### if - elif - else

In [ ]:
x = input("enter x:")
if x> 10:
    print "x is greater than 10"
elif x<1:
    print "x is less than 1" 
else:
    print "Number is in the required range"

#### The while statement

In [ ]:
# Program to count backwards
x = input("Enter a number:")
while x>0:
    x -=1
    print x, #'comma' causes print to print in same line. 
print "."
print "Finished counting backwards"
# To print in same line in python 3 use print(x, end=" ")

#### Break and continue

In [11]:
# Enter password
x="abc"
while x!="PH755":
    x = input("Enter password in quotes:")
    if x=="PH755":
        print "Welcome!"
    if x=="quit":
        break
    print "Enter 'quit' to exit"

Enter password in quotes: "abc"


Enter 'quit' to exit


Enter password in quotes: "PH755"


Welcome!
Enter 'quit' to exit


In [26]:
x =10
while x>0:
    x -=1
    if x==5:
        continue
    print x,

9 8 7 6 4 3 2 1 0


In [18]:
x =1
print x

1


In [ ]:
# Print positive odd numbers less than a number
x=int(input("Enter a number :"))
while x>0:
    if x%2 !=0:
        x -=1
        continue # skips a step in the while loop
        print x
    else:
        x-=1
        print x,

In [ ]:
# Fibonacci sequence
f1 = 1
f2 = 1
next = f1 + f2
while f1 <=1000:
    print f1,
    f1 = f2
    f2 = next
    next = f1+f2

##### Exercise : Catalan numbers
The Catalan numbers $C_n$ are a sequence of integers that play an important role in quantum mechanics and theory of disordered systems. For more information, see this [wiki page](https://en.wikipedia.org/wiki/Catalan_number). They are given by
$$ C_0 = 1$$
$$ C_{n+1} = \frac{4 n + 2}{n+2}C_n$$
Write a program that prints in increasing order all Catalan numbers less than or equal to one billion.

In [ ]:
# Write your solution here!


### Lists and Arrays

Variables store single values. Often we would want to store a set of values. Eg:- In three dimensions, position vector ${\bf r}$ is a list of three numbers. We would also want to work with matrices. 

For this purpose, Python provides objects known as *containers*. We will deal with lists and arrays.

#### Lists

In [27]:
# List is a collection of quantities
[1,2,3]

[1, 2, 3]

In [28]:
# Not all elements in a list need to be of same type. 
[1,2.,3. +4j,"a"]
# However, in most cases elements of a list will be of same type.

[1, 2.0, (3+4j), 'a']

In [29]:
# a variable can be set equal to a list
r = [1,2,3]
r

[1, 2, 3]

In [30]:
# One can constitute a list using variables
x, y, z = 2, 3, 4
r = [x**2, y**2, z**2]
print r

[4, 9, 16]


In [31]:
# Elements in a list can be accessed as follows:
print r

In [32]:
print r[0], r[1], r[2]
print r[-1], r[-2], r[-3]
print r[0:2]

4 9 16
16 9 4
[4, 9]


In [33]:
a = [2,4,6,8,10]
a[1:3]

[4, 6]

In [34]:
# One can also change elements of a list
print r
r[1]=0
r

[4, 9, 16]


[4, 0, 16]

##### Trivia 

The `In` and `Out` written in front of each cell is a list. Try it out.

In [37]:
Out[33]

[4, 6]

In [39]:
# One can apply certain operations on entire list. Eg:-
r = [1., 1.5, 2.5]
print "r = ", r
print "sum of r is :", sum(r) # adds all elements
# length of a list
print "Number of elements in r is", len(r)
# So, one could add above two statements to find mean
mean = sum(r)/len(r)
print "Mean of list r is :", mean


r =  [1.0, 1.5, 2.5]
sum of r is : 5.0
Number of elements in r is 3
Mean of list r is : 1.66666666667


In [59]:
# One can add more elements in to a list using the following command
r = [1., 1.5, 2.5]
r.append(4)
print " Appended a new element to r. Now r is :", r

 Appended a new element to r. Now r is : [1.0, 1.5, 2.5, 4]


In [60]:
r.reverse()
print r

[4, 2.5, 1.5, 1.0]


In [61]:
# One can remove values from end of a list
r = [1., 1.5, 2.5, 4.]
print r.pop()
print r

4.0
[1.0, 1.5, 2.5]


In [63]:
# Empty list 
r=[]
print r

[]


In [68]:
from math import sin
r =[1.,2.,3.]
sin(r)

TypeError: a float is required

In [69]:
# One can map operations to each elements of a list
from math import sin, pi
r = [0, pi/4, pi/2, 3*pi/4, pi]
map(sin,r)

[0.0, 0.7071067811865475, 1.0, 0.7071067811865476, 1.2246467991473532e-16]

In [70]:
# What happens when we add two lists:
a = [0,1,2]
b = [1,1,1]
print " a + b = ", a+b
# What happens when we multiply a list by an integer:
print " 3*a =", 3*a
# You cannot 

 a + b =  [0, 1, 2, 1, 1, 1]
 3*a = [0, 1, 2, 0, 1, 2, 0, 1, 2]


In [73]:
# Lists can be multidimensional i.e. lists can contain lists.
a =[0,1,2]
b = [3,4,5]
c=[a,b]
print c
print " The 01 and 12 elements are :", c[0][1], c[1][2]

[[0, 1, 2], [3, 4, 5]]
 The 01 and 12 elements are : 1 5


In [77]:
c[0][2]

2

#### Arrays

Arrays are also an ordered list with the following conditions:

1. Number of elements in an array is fixed, *i.e.* you cannot use `append`.

* The elements of an array are all of the same type.

* Arrays are like vectors or matrices. One can do arithmetic operations on them. 

* Arrays can have multiple dimensions

* Operations on arrays are faster than those on lists.

The package `numpy` provides a lot of functions for creation and manipulation of arrays.

In [1]:
import numpy as np

In [81]:
# An array of zeros
np.zeros([3],int) 
# Try the following: (1) remove float (2) replace float by int or complex.

array([0, 0, 0])

In [84]:
# An array of ones
np.ones([3,2],float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
# An empty array
np.empty(3)
# It is not really empty, it contains random numbers 
# littering around in computers memory.

array([4.68708024e-310, 4.68708024e-310, 6.89991215e-310])

In [91]:
# Convert a list to an array
r = [1.,2, 3]
np.array(r,float)

array([1., 2., 3.])

In [92]:
# One could create an array by reading data from a file. 
addition_table=np.loadtxt("/home/sreenath/Desktop/sample_data.txt",float)
print addition_table
# Note that one need to give the correct location.

[[1. 1. 2.]
 [1. 2. 3.]
 [1. 3. 4.]
 [1. 4. 5.]
 [1. 5. 6.]]


#### Accessing elements in arrays

In [93]:
# To access a single element
print "(0,2) element is:", addition_table[0,2]

(0,2) element is: 2.0


In [96]:
# To access all elements in a row
print "all elements in the row 1 is : ", addition_table[1,:]

 all elements in the row 1 is :  [1. 2. 3.]


In [97]:
# To access all elements in a column
print "all elements in the column 2 is : ", addition_table[:,2]

all elements in the column 2 is :  [2. 3. 4. 5. 6.]


In [98]:
# To access a portion of the array:
print "first three rows and last two columns are:"
print addition_table[0:3,1:3]
# This is known as slicing

first three rows and last two columns are:
[[1. 2.]
 [2. 3.]
 [3. 4.]]


In [99]:
# Last two columns and rows
print "last two columns and rows"
addition_table[-2:,-2:]

last two columns and rows


array([[4., 5.],
       [5., 6.]])

#### Arithmetic with arrays

In [100]:
# product with scalars
a = np.array([1,2,3])
print a
print a+1
print a*2
print 2*a -1
print a/2.

[1 2 3]
[2 3 4]
[2 4 6]
[1 3 5]
[0.5 1.  1.5]


In [54]:
# Arrays can be added to each other
a = np.array([[2,3],[4,5]],float)
print "a =", a
#print "b=",b
b= np.ones([2,2], int)
print "b =", b
print "a+b =",a+b


a = [[2. 3.]
 [4. 5.]]
b = [[1 1]
 [1 1]]
a+b = [[3. 4.]
 [5. 6.]]


In [44]:
# arrays can be subtracted 
a-b

array([[1., 2.],
       [3., 4.]])

In [46]:
# arrays can be multiplied : element wis addition
a*b

array([[2., 3.],
       [4., 5.]])

In [105]:
# arrays can be divided : element wise division
b/a

array([[0.5       , 0.33333333],
       [0.25      , 0.2       ]])

In [50]:
# To perform matrix multiplication
np.dot(a,b)

array([[5., 5.],
       [9., 9.]])

#### Shape and size of an array

In [55]:
print a
a.size

[[2. 3.]
 [4. 5.]]


4

In [58]:
a.shape

(2, 2)

In [64]:
a = np.random.rand(3,5)
print a
print np.size(a)
print np.shape(a)

[[0.97020423 0.00896829 0.74023906 0.6730588  0.09990151]
 [0.37159001 0.20828277 0.47122424 0.39712888 0.33491136]
 [0.80880475 0.70538637 0.88052882 0.70376181 0.24893786]]
15
(3, 5)


In [66]:
a.reshape(5,3)

array([[0.97020423, 0.00896829, 0.74023906],
       [0.6730588 , 0.09990151, 0.37159001],
       [0.20828277, 0.47122424, 0.39712888],
       [0.33491136, 0.80880475, 0.70538637],
       [0.88052882, 0.70376181, 0.24893786]])

In [57]:
##### Exercise:
#Find out the use of the following functions:
print a
print np.max(a)   
print np.min(a)

[[2. 3.]
 [4. 5.]]
5.0
2.0


#### Python treats array names as pointers 

In [67]:
# Consider the following example. Is the answer what you had expected?
a = 2
b = a
a = 3
print a, b 

3 2


In [68]:
# Now consider the following example. Is the answer what you had expected?
a = np.zeros(2)
b = a
a[0]=2
print a
print b
# i.e. a points to a memory location and when one assigns 
# b = a, what Python really does is to make b also point to 
# the same memory location.

[2. 0.]
[2. 0.]


In [69]:
# So, how does one actually make a copy of an array
a = np.zeros(2)
b = np.copy(a)
a[0]=2
print a
print b

[2. 0.]
[0. 0.]


#### range and arange operators

In [71]:
# range produces a list
print range(1,11,2)# range ( starting number, n+1th number, step size)
print range(11) # here starting number is zero, n+1 th number is, step size =1

[1, 3, 5, 7, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [74]:
# arange produces an array
np.arange(1.,2.,.1)# add float or complex

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

### for loop

In [78]:
# Print out the multiplication table for 2 :
for i in np.array([1,2,3,4]):
    print "2 *",i,"=",2*i

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8


### User defined function

Often there will be steps in calculation that we want to repeat several number of times. To saveeffort and readability of the code, one can write them as functions.

In [93]:
# Function to compute factorial
def factorial(n):
    f =1.0
    for k in range(1,n+1):
        f*=k
    return f

In [94]:
factorial(5)

120.0

##### Exercise : Pascal's triangle :

   a. Write a function `binomial(n,k)` to compute binomial 
    coefficient. Make sure to return answers as integer. 
    Make sure that it gives $1$ for `k=0`.
    
   b. Print out first 10 lines of Pascals triangle 
    i.e n$_{\rm th}$ line will contain binomial(n,0), 
    binomial(n,1), ..., binomial(n,n).
    
   c. Probability of obtaining k heads in n tosses is 
    `binomial(n,k)/2**n`. Write a program to calculate 
    probability of obtaining 40 heads in 100 tosses. 
    Write a program to calculate 40 or more heads in 
    100 tosses. 

In [8]:
# Write the solution here!


1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 
1 8 28 56 70 56 28 8 1 
1 9 36 84 126 126 84 36 9 1 
1 10 45 120 210 252 210 120 45 10 1 


Number of heads = 40
Number of tosses = 100


Probability of obtaining 40 or more heads from 100 tosses is 0.982399899891


##### Exercise : Prime numbers :

1. Write a function to compute whether a number is prime or not. 

2. Use that function to print all primes less than a number n. 

#### Some more details about lists and arrays

In [16]:
a_list=[1.,2, 3+5j]
print a_list

[1.0, 2, (3+5j)]


In [17]:
an_array=np.array([1.,2,3+5j])

In [20]:
an_array=np.array([1.,2,3+5j,4.])
an_array

array([1.+0.j, 2.+0.j, 3.+5.j, 4.+0.j])

In [21]:
# We can append to a list
a_list.append(5)

In [22]:
a_list

[1.0, 2, (3+5j), 5]

In [23]:
#One cannot add a number to a list
a_list+1

TypeError: can only concatenate list (not "int") to list

In [24]:
# One can add a number to an array
an_array+1.

array([2.+0.j, 3.+0.j, 4.+5.j, 5.+0.j])

In [27]:
2*a_list

[1.0, 2, (3+5j), 5, 1.0, 2, (3+5j), 5]

In [29]:
print an_array
an_array/2

[1.+0.j 2.+0.j 3.+5.j 4.+0.j]


array([0.5+0.j , 1. +0.j , 1.5+2.5j, 2. +0.j ])

In [83]:
position = np.array([2,3,0.])
velocity = np.array([1,1,1.])

In [84]:
#v dot r
np.dot(position,velocity)

5.0

In [85]:
# It is possible to perform vector operation using lists. 
# But operation using arrays are faster(as I will show below)
# v dot r using list
position_list = [2.,3.,0]
velocity_list = [1.,1.,1.]
a=0.
for i in range(len(position_list)):
    a+=position_list[i]*velocity_list[i]
print a

5.0


In [92]:
position+velocity

array([3., 4., 1.])

### Miscellanious

#### Variables and ranges

One cannot store arbitrarily large numbers. For floats largest number possible is roughly $\pm 1.e308$ (corresponding to $2^{1024}$). When it is larger than this number, we call it an *overflow*. A complex type also has this limit for both real and imaginary parts. Smallest number possible is roughly $10^{-308}$. When the number is smaller, then it is called an *underflow*.
Python can store any number of digits for an integer. However larger the number, slower the operation and more the memory needed. Result of an overflow is `inf` and that of an underflow is `0.0`.

In [1]:
x=1.e309
print x
x = 1.e-330
print x

inf
0.0


In [4]:
# operations with large integers take time
import time as time
start = time.time()
2**100000000
end  = time.time()
print end-start

0.346006155014


#### A note when using `==` condition

Python will round off digits. Hence two numbers may never be exactly equal. 
Because of this reason one should not use equality of two numbers as a condition for `if` statement. 

In [6]:
x=0.1
for i in range(11):
    x +=0.1
    if x==0.8:
        print "We have reached x =",x
    print x,

0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2


In [172]:
# If one indeed wants to do this check, then check their equality up to an error `eps`.
x=0.1
eps = 1.e-6
for i in range(11):
    x +=0.1
    if np.abs(x-0.8) < 1.e-6:
        print "We have reached x =",x
    print x,

0.2 0.3 0.4 0.5 0.6 0.7 We have reached x = 0.8
0.8 0.9 1.0 1.1 1.2


#### Round off error 

In [7]:
from math import sqrt
x = 1.
y = 1. + 1.e-16*sqrt(2)
print 1.e16*(y-x)
print sqrt(2)
# Second print statement is correct value pi. 
#Python keeps only 16 significant digits. Hence, 
#in the first print statement, the answer is correct 
# only to first two significant digits. 

2.22044604925
1.41421356237


#### Formatting in print statement

In [10]:
print "{0} is not equal to {1:.1f}".format(2,3.4526)

2 is not equal to 3.5


#### Program speed

In general a computer can do a million arithmetic operations with in a second. For a billion operation, it will take few minutes to hours. This is still doable. Beyond that one needs more powerful computers.

In [13]:
import numpy as np
start = time.time()
sum(np.arange(1.e8))
end = time.time()
print end-start

9.43891000748


#### Power of vectorization

In [14]:
# v dot r using list
position_list = list(np.random.rand(10000000))
velocity_list = list(np.random.rand(10000000))
a=0.
start = time.time()
for i in range(len(position_list)):
    a+=position_list[i]*velocity_list[i]
end = time.time()
print a
print end-start

2499475.876180908
2.10702896118


In [15]:
position = np.random.rand(10000000)
velocity = np.random.rand(10000000)
start = time.time()
a = np.dot(position,velocity)
end = time.time()
print a
print end - start

2499388.605330687
0.0104489326477
