# Solving Linear Equations

Solve equations of the form
$$
{\bf A}\, {\bf X}\, =\, {\bf v}
$$
where ${\bf A}$ is a $n\, \times\, n$ matrix, ${\bf X}$ is a list of $n$ variables, we are trying to solve for and ${\bf v}$ is an $n$ dimensional array such that above expression is a short notation for

$$
A_{0,0}\,X_0\, +\, ...  \, +\, A_{0,n-1}\, X_n\, =\, v_0 \\
. . . \\
A_{n-1,0}\,X_0\, +\, ...  \, +\, A_{n-1,n-1}\, X_n\, =\, v_{n -1}
$$

### Gauss Elimination

In [2]:
import numpy as np

In [3]:
A=np.array([[2.,1.,4.,1.],[3.,4.,-1.,-1.],[1.,-4.,1.,5.],[2.,-2.,1.,3.]])
A

array([[ 2.,  1.,  4.,  1.],
       [ 3.,  4., -1., -1.],
       [ 1., -4.,  1.,  5.],
       [ 2., -2.,  1.,  3.]])

In [4]:
v=np.array([-4.,3.,9.,7.])
v

array([-4.,  3.,  9.,  7.])

In [19]:
A=np.array([[2.,1.,4.,1.],[3.,4.,-1.,-1.],[1.,-4.,1.,5.],[2.,-2.,1.,3.]])
v=np.array([-4.,3.,9.,7.])
N = len(v)
print "Performing Gauss Elimination"
print"=============================="
for i in range(N):
    denominator = A[i,i]
    A[i,:]/=denominator
    v[i]/=denominator
    for j in range(i+1, N):
        multiplier = A[j,i]
        A[j,:] -= A[i,:]*multiplier
        v[j] -= v[i]*multiplier
print "A =", A
print "v =", v

Performing Gauss Elimination
A = [[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
v = [-2.   3.6 -2.   1. ]


### Backsubstitution

In [51]:
X =np.zeros(N)
X

array([0., 0., 0., 0.])

In [53]:
for i in range(N-1, -1, -1):
    X[i] = v[i]
    for j in range(i+1,N):
        X[i] -= A[i,j]*X[j]
print "Solution is X =", X

Solution is X = [ 2. -1. -2.  1.]


### Pivoting

If the first element in the first row is zero. Gauss elimination would not work. One has to exchange it with a row whose first element is non-zero. This is known as pivoting.

In partial pivoting, we exchange the $m^{\rm th}$ row with a row whose first element is farthest from zero. Here m refers to the row whose first element we are trying to change to 1.

In [106]:
A=np.array([[2.,1.,4.,1.],[3.,4.,-1.,-1.],[1.,-4.,1.,5.],[2.,-2.,1.,3.]])
v=np.array([-4.,3.,9.,7.])
N = len(v)
y = np.zeros(N)
print "Performing Gauss Elimination with partial pivoting"
print"===================================================="
for i in range(N):
    y =np.copy(A[i,:])
    w = v[i]
    m = i
    for k in range(i+1,N):
        if A[m,i]< A[k,i]:
            m = k
    A[i,:] = np.copy(A[m,:])
    A[m,:] = np.copy(y)
    v[i] = v[m]
    v[m]=w
    denominator = A[i,i]
    A[i,:]/=denominator
    v[i]/=denominator
    for j in range(i+1, N):
        multiplier = A[j,i]
        A[j,:] -= A[i,:]*multiplier
        v[j] -= v[i]*multiplier
print "A =", A
print "v =", v

Performing Gauss Elimination with partial pivoting
A = [[ 1.          1.33333333 -0.33333333 -0.33333333]
 [-0.          1.         -2.8        -1.        ]
 [-0.         -0.          1.          0.0877193 ]
 [ 0.          0.          0.          1.        ]]
v = [ 1.         3.6       -1.9122807  1.       ]


In [107]:
X =np.zeros(N)
X

array([0., 0., 0., 0.])

In [108]:
for i in range(N-1, -1, -1):
    X[i] = v[i]
    for j in range(i+1,N):
        X[i] -= A[i,j]*X[j]
print "Solution is X =", X

Solution is X = [ 2. -1. -2.  1.]
